/*************************************************
**	CODA.INC: VISIBILITY PLOT for FX DATA	**
**	AUTHOR:		KAMENO S.						**
**	CREATED:	1995/8/17						**
**************************************************/

long	err_code;		/* Error Flag which CODA returns */
char	dhome[128];		/* CFS Data Home Directory */
char	oname[128];		/* CFS Observation Directory */
char	ofull[128];		/* CFS Observation Full Path */
char	srdir[128];		/* CFS Search Table Sub-Directory */
char	lgdir[128];		/* CFS LOG Directory */
char	crdir[128];		/* CFS Baseline Directory */
char	vcdir[128];		/* CFS Video-Convertor Directory */
char	cbdir[128];		/* CFS Calib Directory */
char	cthed[128];		/* Admin Table Header File */
char	cttab[128];		/* Admin Table Table File */
char	srtab[128];		/* Search Table File */
char	headf[128];		/* Header File */
char	histf[128];		/* History File */
char	corrf[128];		/* Correlation Data File */
char	flagf[128];		/* Flag Data File */
char	antef[128];		/* Antenna Calibration File */
char	gcalf[128];		/* Geometorical Calibration File */
char	fcalf[128];		/* Frequency Calibration File */
char	pcalf[128];		/* Phase Calibration File */
char	bcalf[128];		/* Baseline Calibration File */
char	lcalf[128];		/* Calibration File */
